name: template-filler

services:
  template-filler:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-filler:latest
    container_name: template-filler
    restart: unless-stopped
    ports:
      - "127.0.0.1:5082:8080"
    volumes:
      - ./data:/app/App_Data
    networks:
      proxy:
        aliases:
          - template-filler

networks:
  proxy:
    external: true
    name: shared-proxy
